<template>
  <div>
    nuxt page view 입니다.
    <UButton>
      sldkfj
    </UButton>
    <div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div><div>
      <UButton>
        sldkfj
      </UButton>
    </div>
  </div>
</template>
<script setup lang="ts">
</script>